### ISSUE TITLE
runscript is not working

### ISSUE THREAD

**Issue by pankajps** [Silv3rHorn/BulkStrike#1]
Hi, 

 runscript is not working, giving argv error, Even if I am trying "runscript -CloudFile="test1" ", then it's returning True, but Nothing happens on the actual machine.

runscript  c:\windows\system32\wusa.exe "c:\windows10.0-kb4538461-.msu" /quiet /norestart

Host ID : ******
Complete: False
Stdout  :
Stderr  :
Errors  : [{'code': 40012, 'message': 'Max args is 0. 4 were provided'}]

---
RTR session started...
type 'bulk <file path>' to execute multiple commands
(type exit to end) > runscript -CloudFile="test1"
Host ID : *************
Complete: True
Stdout  :
Stderr  :
Errors  : []

# nothing happens on actual server

**Comment by Silv3rHorn** [comment]
Hi,

I verified and had no issues using the runscript command from my end. Following are a couple of things you can try to troubleshoot this

- Use this command instead: runscript -CloudFile="test1" **_-CommandLine=""_**
- Try running the same scripts using RTR feature in CrowdStrike Falcon console to verify that the scripts perform as intended

**Comment by pankajps** [comment]
It's not giving argument error if I am using with -ComandLine switch, and giving True but actually not executed on the machine.

(type exit to end) > runscript -CommandLine="c:\windows\system32\wusa.exe c:\test.exe /quiet /norestart"
Host ID : *************
Complete: True
Stdout  :
Stderr  :
Errors  : []

--

Is there any switch that can refresh/extend the token time or RTR session time? If put command is taking time, then the connection get break after 590 seconds.


{'code': 50401, 'message': 'Exceeded maximum read timeout: 590.00s'}

**Comment by Silv3rHorn** [comment]
Unfortunately, 600 seconds is the hard limit set by CrowdStrike for the duration of script execution. I don't think there is any way to bypass that.

**Comment by Silv3rHorn** [comment]
As for the runscript error that returns True without execution, pls verify that the runscript command can be successfully executed via CrowdStrike RTR console.

**Comment by pankajps** [comment]
There is an API Endpoint to refresh to keep the session active, I am wondering how to add this.


Roughly every 5 minutes, refresh your Real Time Response session using POST **/real-time-response/combined/batch-refresh-session/v1**

Every 5 minutes, make a POST **/real-time-response/entities/refresh-session/v1** request to keep your session active.

As in the Falcon console, a Real Time Response session automatically ends after 10 minutes. We recommend sending a refresh request every 5 minutes to maintain your connection.

**Comment by Silv3rHorn** [comment]
That wasn't implemented perfectly in BulkStrike. It only refreshes the session as necessary when a new command is executed. Hence, if your script command had been running for 10 mins, the session would timeout as well. 

However, this wouldn't matter as CrowdStrike does not allow scripts to be executed for more than 10 mins. Even if refresh session was implemented perfectly, your script would still be terminated prematurely by CrowdStrike as it had exceeded the maximum script execution duration of 10 mins.

Refer to https://www.reddit.com/r/crowdstrike/comments/dyd7o2/rtr_timeout/ for workarounds.

**Comment by pankajps** [comment]
Thanks, yeah it worked, Nice one
