### ISSUE TITLE
ExecuteKape.ps1 and kape timeout question

### ISSUE THREAD

**Issue by theredmoose** [Silv3rHorn/BulkStrike#2]
This is not an issue but a question.  

What do you have in your ExecuteKape.ps1 script in the demo?  I have been writing some familiar code but you are way ahead of me.

Also, do you run into issues where the kape execution times out?  I set my --timeout= to 10min which I think is the max.  However, I still encounter issues.  I think this is what your Future work "create parallel thread" task is about.  I came across another discussion about launching kape in a separate process however this means that other 'cleanup' tasks are not performed after kape is complete.

Thanks for your work.  Let me know if there is a better place to message you.

**Comment by Silv3rHorn** [comment]
Hi,

My ExecuteKape.ps1 does not contain anything special - 
```
.\kape\kape.exe --tsource C: --tdest .\kape-output --target EventLogs,RegistryHives --zip host_artifacts
cd kape-output
mv *.zip host_artifacts.zip
```
I find 10mins (the max restriction) more than enough time for me to execute KAPE on remote machines as I only collect forensic artifacts and not do any processing. Moreover, CrowdStrike has more than enough event telemetry (EAM)  available, and I find myself collecting only the Event Logs and Registry Hives most of the time.

To get around the 10mins restriction, I would recommend splitting your script into multiple parts, with each part collecting different forensic artifacts (ordering from the most essential to the least). Even if the target host goes offline, you would still have artifacts collected from previous script executions for analysis.

I hope this helps.

Regards.
