### ISSUE TITLE
Option to change API Server

### ISSUE THREAD

**Issue by Lovecore** [Silv3rHorn/BulkStrike#4]
Currently, the `cs_methods.py` file explicitly lists the `SERVER` value as https://api.crowdstrike.com. If this value can be placed in a the `~./bulkstrike` directory with the other variables, it would resolve the 401 issues if you're on a different api uri, such as `api.us-2.crowdstrike.com`

**Comment by Silv3rHorn** [comment]
Hi Lovecore, thanks for raising this issue. I overlooked that there are other API servers available. WIll try to implement what you suggested over the next week.

**Comment by Silv3rHorn** [comment]
Hi Lovecore, I have added the support for other API servers in the latest release - https://github.com/Silv3rHorn/BulkStrike/releases/tag/20210601. You will have to run `bulkstrike configure` first to change to your desired API server. Pls test it out and let me know how it goes. Thanks.

**Comment by Lovecore** [comment]
Looks good. We can close this issue. Thanks for the tool!
