### ISSUE TITLE
How to send bulk cmds to rtr sessions in one line?

### ISSUE THREAD

**Issue by theredmoose** [Silv3rHorn/BulkStrike#6]
Is it possible to send the script execution to the startrtr session in one line?  or at least pipe it via the cmd line?

Something like this, but this doesn't work... 

bulk_strike.py start_rtr -f aidlist.txt  --log -i  i cb2fc1f9aaefdsafdasfdas632448879e1_6f99d78ffffffffffff81f

**Comment by Silv3rHorn** [comment]
Hi,

Apologies for the late reply. 

Bulkstrike is not able to do that currently, but I do think it's a good idea.

Unfortunately, I recently left my job, and no longer have access to Crowdstrike Falcon to work on this. I will note this down and explore further when I regain access.
